version: '3'

services:
  app:
    image: node:16.20.0-slim
    working_dir: /usr/src/app
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install --quiet --no-optional --no-fund --loglevel=error && npm run build && npm run start:prod"
